//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTYS_PROJE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PansiyonDBEntities : DbContext
    {
        public PansiyonDBEntities()
            : base("name=PansiyonDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kasa> Kasa { get; set; }
        public virtual DbSet<Musteriler> Musteriler { get; set; }
        public virtual DbSet<OdaKayitlari> OdaKayitlari { get; set; }
        public virtual DbSet<Odalar> Odalar { get; set; }
        public virtual DbSet<PremiumOda> PremiumOda { get; set; }
        public virtual DbSet<Rezervasyonlar> Rezervasyonlar { get; set; }
        public virtual DbSet<StandartOda> StandartOda { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<VipOda> VipOda { get; set; }
    }
}
